name: 'simple workflow pm2'
on: [push] #event (untuk meng trigger workflow)
jobs:
 check-pm2-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #action
      - uses: actions/setup-node@v1
      - run: npm install -g pm2
      - run: pm2 -v